spring:
  profiles:
    group:
      "dev": devDB,devMVC,devCache
    active: dev
  main:
    banner-mode: off
  mail:
    host: smtp.qq.com
    username: 3503726156@qq.com
    password: yrybcmhcbiyldbid


logging:
  level:
    root: info
